Update the whole meta-layer for Yocto Kirkstone
Current patch tries to solve only obvious build issues and mostly
is a result of upgrading by using variuos scripts located
at "poky/scripts/contrib/".

Unfortunately, "convert-overrides.py" script has missed some stuff to update
in displaymanager (DM_CONFIG) and meta-xt-rcar-proprietary (RESULT_NAME)
recipes, so update manually there.
BTW, the old syntax in RESULT_NAME_* variable leads to nasty issue
when fetching:
ERROR: kernel-module-gles-1.0-r0 do_fetch: Fetcher failure:
Unable to find file file://GSX_KM_H3.tar.bz2 anywhere
This is because the default name ^^???-NOT-SUPPORTED-???^^ which is
explicitly set in the recipe wasn't overriden by SoC's name.

It should be noted that convert-overrides.py produces one wrong change
which must not be taken into the account:

--- a/meta-xt-rcar-domx/recipes-security/optee/optee-os_git.bb
+++ b/meta-xt-rcar-domx/recipes-security/optee/optee-os_git.bb
@@ -33,7 +33,7 @@ EXTRA_OEMAKE = "-e MAKEFLAGS= \
                   CFG_ARM64_core=y \
                   CFG_VIRTUALIZATION=y \
                   CROSS_COMPILE_core=${HOST_PREFIX} \
-                  CROSS_COMPILE_ta_arm64=${HOST_PREFIX} \
+                  CROSS_COMPILE_ta:arm64=${HOST_PREFIX} \
                   ta-targets=ta_arm64 \
                   CFLAGS64=--sysroot=${STAGING_DIR_HOST} \
                   CFG_SYSTEM_PTA=y \

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>