kmscube: Use correct header instead of gl3ext.h stub
The problem was that kmscube failed to compile when using
prebuilt graphic binaries because required gl3ext.h was
absent in the target archive, but should be present as
gles-module recipe already contains the needed stub.

texturator.c.o' -c ../git/texturator.c
| ../git/texturator.c:33:10: fatal error: GLES3/gl3ext.h: No such file or directory
|    33 | #include <GLES3/gl3ext.h>

Resolve the issue in another way by updating the kmscube to use
correct header. The corresponding fix was ported from "kirkstone"
branch. Next patch will remove gl3ext.h stub from gles-module recipe.

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>